### PR TITLE
Simple arbitrary logic batches

### PR DESCRIPTION
**Pull request by jtremback**
This is a tracking PR for arbitrary logic functionality. This is coded for expedience to meet the Feb. 2 testnet goal, and could do a lot of things differently. Still it is secure and should have good performance.

I have created a duplicate of `submitBatch`, called `submitLogicBatch`. This processes a batch of transactions, where each transaction

- First transfers tokens to a "logic contract" which contains the arbitrary logic. If you don't need to transfer any tokens, I think you can just set the amount to 0 (todo: need to test this).
- Then calls a function on the logic contract. The function name and arguments are abi encoded in the normal way and are passed in as `bytes`.

Limitations:

Batches are still single token. If you need to transfer multiple types of tokens to a logic contract for an operation, it needs to be done in several batches, introducing latency and making the operation non-atomic. The main reason for limiting batches to a single token in `submitBatch` has to do with fee calculation. Since arbitrary logic has to have a completely different fee calculation technique anyway, there is no downside to making arbitrary logic batches multi-token. However, it will require a re-architecting of the API, and we might as well roll that in with https://github.com/althea-net/peggy/issues/141

Still, this arbitrary logic implementation should work for a wide variety of use cases already. I'm going to want to finish https://github.com/althea-net/peggy/issues/141 before merging this into mainline Peggy though.

### CODE REVIEW

**Comment by jtremback** [comment]
Integration tests / valset-stress (pull_request) is failing, however my code does not touch anything related to the integration tests

**Comment by jtremback** [comment]
We need to use `pragma experimental ABIEncoderV2;` in this PR, since the arbitrary logic functionality requires passing in arrays of bytes. 

AFAIK, ABIEncoderV2 does not have any security vulnerabilites, but we have stayed away from using it in the past, since it is "experimental". Solidity 8 integrates it and no longer requires the "experimental" pragma. We cannot yet upgrade to Solidity 8, because Zeppelin has not yet upgraded AFAIK.

I think using this pragma is safe, but I just wanted to flag the issue.

**Comment by jkilpatr** [comment]
> We need to use `pragma experimental ABIEncoderV2;` in this PR, since the arbitrary logic functionality requires passing in arrays of bytes.
> 
> AFAIK, ABIEncoderV2 does not have any security vulnerabilites, but we have stayed away from using it in the past, since it is "experimental". Solidity 8 integrates it and no longer requires the "experimental" pragma. We cannot yet upgrade to Solidity 8, because Zeppelin has not yet upgraded AFAIK.
> 
> I think using this pragma is safe, but I just wanted to flag the issue.

I've been a proponent of unbatched arbitrary logic since we first started designing this, with the argument that it would reduce complexity although exactly how much it would reduce complexity was unknown. I think that having to import v2 ABI encoding is exactly the sort of thing I was talking about.

That being said the tests pass so clearly we haven't changed too much. From what I understand importing this upgrades all ABI encoding in the contract. The risks there are that there's a bug in the encoder, or that people in the ecosystem have trouble encoding call to our transaction because we're solidity 7 but using solidity 8 encoding.

1) if we can prove that the encoding logic we're using with this import is identical to v8 then there's no security risk (beyond the risks of using v8 which I will consider negligible) 
2) We should do a quick check of what it takes to call this endpoint using existing encoding tooling, see if we get any speedbumps because of these libraries trying to auto detect encoding.

If the above two things are not big issues lets roll with it as I believe it's an acceptable trade-off for higher efficiency.

**Comment by jtremback** [comment]
I'll just take this opportunity to do a thorough comparison of different approaches.

1. Batched logic calls (this PR)
2. Unbatched logic calls (@jkilpatr's suggestion)

**(1)** Batched logic calls are pretty straightforward, we just add another line to submitBatch which calls a function on the address funds are being transferred to. This allows Gravity to transfer funds to a logic contract, and then have the logic contract do something with those funds. 

The downside being discussed here is that the function call must be encoded as `bytes`, which is an array type. A batch must then contain an array of these `bytes`, which is an array of arrays, which cannot be passed into a function without abiencoderv2.

The benefit of this pattern is that the logic contract can be extremely simple, and only needs to contain the code to do one operation. It does not need to know anything about how Gravity works, or batches or anything. I think this method provides the best developer experience for logic contract developers.

Another possible future benefit is that this transitions pretty smoothly to multi-token batches, or other batching optimizations (nonce-free batches, etc). On the Gravity side, since it is so similar to the basic `submitBatch` function, it is easy to add the same logic. On the logic contract side, nothing at all needs to change since the logic contracts are so simple.

**(2)** Unbatched calls simply do the signature checks etc. to check that the validator set has signed off on a single logic contract call, and a single token transfer to that logic contract. This call then goes out to a logic contract which may contain a loop to execute a batch of transactions to save on gas.

This is the cleanest on the Gravity side. We defer most decisions and work around batching to the logic contract. As @jkilpatr points out, we don't need abiencoderv2 in Gravity since any arrays of arrays in a batch being passed to a logic contract will be contained in the `bytes` blob that is being passed to it.

The downside is that logic contracts now need to include batching logic in them. This is not a huge deal, but it definitely adds overhead, and makes the logic contracts much less simple. We can make it easier by supplying logic contract authors with a batching library. However, any upgrades to batching will not be shared with already-deployed logic contracts.

An option to preserve the simplicity of logic contracts while using unbatched logic calls is to make a middleware batching contract. This would be called once by Gravity, and contain a loop to make a bunch of calls to simple logic contracts. This would incur some extra overhead by requiring another ERC20 transfer to the batching contract, and it adds complexity.

**Comment by jtremback** [comment]
This PR should not be merged until we figure out the nonce situation.

**Pull request closed without merging**
