### PR TITLE
Bech32ibc integration

### PR DESCRIPTION
**Pull request by antstalepresh**
Bech32ibc is to send assets on a native chain or via cross-chain based on bech32 prefixes.
For the prefixes registered on bech32ibc, if it does not have a native prefix for bech32, it is sent via the IBC channel to the target chain.

The process of sending assets from one chain to another using bech32ibc module. https://github.com/osmosis-labs/bech32-ibc/tree/relay_test#process-of-sending-assets-via-bech32ibc-and-bech32ics20

### CODE REVIEW

**Comment by ValarDragon** [comment]
Can you add / comment an exåmple of the config parameters that would need to be added via governance or otherwise to enable sending to `osmo1...`?

**Comment by antstalepresh** [comment]
> Can you add / comment an exåmple of the config parameters that would need to be added via governance or otherwise to enable sending to `osmo1...`?

Add the comment on this github thread or put on README?

**Comment by ValarDragon** [comment]
Can we do both?

**Comment by antstalepresh** [comment]
> Can we do both?

Done

**Review by jkilpatr — APPROVED** [review]
This looks good, not totally sure we want to use bech32ics20 at this time but lets play around with it on our next testnet.

**Pull request merged**
